/* ============================================================
   VIZ — peça visual por conteúdo. Diversidade: gráficos,
   infográficos, planograma, placeholders de foto, esquemáticos.
   Tipos: bars, migration, versus, funnel, matrix, planogram,
   steps, balance, packmap, photo, personas, checklist,
   metrics, donut, journey.
   ============================================================ */
const VIZ = {
 'hnk-exp-01':{type:'bars',unit:'%',caption:'Barreiras ao consumo fora do lar',
   data:[{l:'Menos frequência',v:30},{l:'Preço',v:35,hi:1},{l:'Tráfego no PDV',v:44,hi:1},{l:'Segurança',v:13}]},
 'hnk-exp-02':{type:'balance',caption:'Por que sair de casa vale a pena',
   left:{title:'Em casa',items:['Custo controlado','Privacidade','Menos exposição']},
   right:{title:'No bar',items:['Encontro e ritual','Atmosfera e serviço','Cerveja muito gelada']}},
 'hnk-exp-03':{type:'migration',caption:'Migração de mix no On-Trade',
   data:[{l:'Economy',from:22,to:19},{l:'Affordable Premium',from:8,to:10},{l:'Regular Premium',from:11,to:13}]},
 'hnk-exp-04':{type:'funnel',caption:'Onde a HEINEKEN vaza valor',
   steps:[{l:'Marca forte (pull)',note:'abre portas'},{l:'Cadastro',note:'fricção de acesso'},{l:'Compra direta',note:'14% vs 66% Ambev',leak:1},{l:'Entrega',note:'dias rígidos',leak:1},{l:'Disponibilidade',note:'ruptura',leak:1},{l:'Rotação',note:'recompra'}]},
 'hnk-exp-05':{type:'versus',caption:'Restaurant C/D · Heineken vs Ambev',aLabel:'Heineken',bLabel:'Ambev',
   pairs:[{l:'Entrega',a:60,b:79},{l:'Pagamento',a:62,b:70},{l:'Prazo',a:52,b:64},{l:'Preço',a:55,b:62},{l:'Promoções',a:43,b:52}]},
 'hnk-exp-06':{type:'bars',unit:'%',caption:'Reação do shopper à ruptura',
   data:[{l:'Bar A/B: troca de bebida',v:40},{l:'Bar A/B: vai a outro local',v:37,hi:1},{l:'ASI: outro estabelecimento',v:55,hi:1},{l:'ASI: abandona cerveja',v:38}]},
 'hnk-exp-07':{type:'planogram',caption:'Arquitetura fria por missão e giro',
   shelves:[
     {tier:'TOPO',label:'Premium / moderação',items:[{n:'Heineken',c:'p-bar-ab'},{n:'0.0',c:'p-bar-ab'},{n:'Long neck',c:'p-bar-ab'}]},
     {tier:'MEIO',label:'Alta conversão',items:[{n:'Amstel',c:'p-bar-cd'},{n:'600ml',c:'p-bar-cd'},{n:'Líder do PDV',c:'p-bar-cd'}]},
     {tier:'BASE',label:'Valor / volume',items:[{n:'Lata',c:'p-planograma'},{n:'1L',c:'p-planograma'},{n:'Packs',c:'p-planograma'}]}
   ]},
 'hnk-exp-08':{type:'bars',unit:'%',caption:'Pedidos feitos via vendedor',
   data:[{l:'Bar A/B',v:82,hi:1},{l:'Bar C/D',v:81,hi:1},{l:'Restaurant C/D',v:74},{l:'ASI',v:74}]},
 'hnk-exp-09':{type:'bars',unit:'%',caption:'Como o vendedor é lembrado (Bar A/B)',
   data:[{l:'Motiva a compra',v:43,hi:1},{l:'Aconselha portfólio',v:13},{l:'Treina a equipe',v:4}]},
 'hnk-exp-10':{type:'matrix',caption:'Papéis do portfólio',
   axisX:['Mainstream','Premium'],axisY:['Construção','Consolidado'],
   cells:[{x:1,y:1,l:'Heineken',active:1},{x:1,y:0,l:'Ultimate'},{x:0,y:1,l:'Amstel',active:1},{x:0,y:0,l:'0.0 · extensões'}]},
 'hnk-exp-11':{type:'metrics',caption:'Amstel · equity FY25 (Kantar)',
   data:[{l:'Demand Power',from:'5,7',to:'6,0',dir:'up'},{l:'Meaningful',from:133,to:140,dir:'up'},{l:'Different',from:119,to:111,dir:'down'},{l:'High Quality',from:'39%',to:'37%',dir:'down'}]},
 'hnk-exp-12':{type:'matrix',caption:'Escala × Adequação ao outlet',
   axisX:['Baixa adequação','Alta adequação'],axisY:['Baixa escala','Alta escala'],
   cells:[{x:1,y:1,l:'Plataforma modular',active:1},{x:0,y:1,l:'Kit genérico'},{x:1,y:0,l:'Hiperlocal'},{x:0,y:0,l:'Peças soltas'}]},
 'hnk-exp-13':{type:'donut',caption:'Dimensões que decidem o investimento',
   segments:[{l:'Ocasião / daypart',v:25},{l:'Audiência',v:20},{l:'Economia',v:20},{l:'Infraestrutura',v:15},{l:'Ambição do dono',v:12},{l:'Concorrência',v:8}]},
 'hnk-exp-14':{type:'photo',img:'bar',caption:'Bar A/B · experiência premium e ambientação'},
 'hnk-exp-15':{type:'bars',unit:'%',caption:'Bar C/D · compra direta e sinalização',
   data:[{l:'Compra direta Heineken',v:14},{l:'Compra direta Ambev',v:66,hi:1},{l:'Placa/preço em C/D',v:30,hi:1},{l:'Placa/preço em A/B',v:21}]},
 'hnk-exp-16':{type:'versus',caption:'ASI · Heineken vs Ambev',aLabel:'Heineken',bLabel:'Ambev',
   pairs:[{l:'Material de PDV',a:25,b:66},{l:'Satisfação c/ entrega',a:56,b:80}]},
 'hnk-exp-17':{type:'packmap',caption:'Pack como estratégia de ocasião',
   packs:[{n:'Long neck',o:'Individual · premium',ic:'bottle'},{n:'600 ml',o:'Compartilhar',ic:'share'},{n:'Lata',o:'Imediato · ASI',ic:'can'},{n:'1 litro',o:'Valor · grupo',ic:'jug'},{n:'Chope',o:'Ritual · frescor',ic:'draft'}]},
 'hnk-exp-18':{type:'funnel',caption:'Funil de influência da brigada',
   steps:[{l:'Escolha inicial',note:'influência baixa',leak:0},{l:'Substituição na ruptura',note:'relevante'},{l:'Ritmo / reposição',note:'alta'},{l:'Upsell e promoção',note:'giro e margem'}]},
 'hnk-exp-19':{type:'matrix',caption:'POS: ativo × problema resolvido',
   axisX:['Comunicação','Infraestrutura'],axisY:['Baixo retorno','Alto retorno'],
   cells:[{x:1,y:1,l:'Geladeira · chopeira',active:1},{x:0,y:1,l:'Menu · fachada'},{x:1,y:0,l:'Balde · copo'},{x:0,y:0,l:'Kit genérico'}]},
 'hnk-exp-20':{type:'funnel',caption:'Funil promocional: até a recompra',
   steps:[{l:'Oferta / combo',note:'atrai'},{l:'Primeiro pedido',note:'sell-in'},{l:'Disponibilidade',note:'exposição',leak:1},{l:'Sell-out',note:'giro real',leak:1},{l:'Recompra',note:'margem incremental'}]},
 'hnk-exp-21':{type:'balance',caption:'A troca do contrato',
   left:{title:'Autonomia',items:['Liberdade de portfólio','Estética autoral','Sem lock-in']},
   right:{title:'Segurança',items:['Equipamento e crédito','SLA de fornecimento','Ativação e ROI']}},
 'hnk-exp-22':{type:'personas',caption:'Dois públicos, o mesmo bar',
   people:[{n:'Geração Z',t:['Estética e validação digital','Networking e novidade','Moderação e 0.0']},{n:'Público 35+',t:['Descompressão e conversa','Atendimento reconhecido','Conveniência e conforto']}]},
 'hnk-exp-23':{type:'checklist',caption:'Licença para permanência no PDV',
   items:['Acesso e iluminação','Banheiro limpo','Atendimento reconhecido','Acústica e assentos','Cerveja muito gelada']},
 'hnk-exp-24':{type:'steps',caption:'Escada de maturidade do outlet',
   steps:[{l:'Sobrevivência',d:'caixa, estoque, frio'},{l:'Controle',d:'dados e calendário'},{l:'Otimização',d:'mix e margem'},{l:'Experiência',d:'serviço e ambiente'},{l:'Comunidade',d:'razão para voltar'}]},
 'hnk-exp-25':{type:'journey',caption:'De evidência a decisão',
   steps:[{l:'Diagnóstico'},{l:'Hipótese'},{l:'Piloto'},{l:'Controle'},{l:'Incremento'},{l:'Escala'}]},
 'hnk-exp-26':{type:'matrix',caption:'Priorização: potencial × prontidão',
   axisX:['Baixa prontidão','Alta prontidão'],axisY:['Baixo potencial','Alto potencial'],
   cells:[{x:1,y:1,l:'Escalar',active:1},{x:0,y:1,l:'Destravar'},{x:1,y:0,l:'Manter leve'},{x:0,y:0,l:'Não priorizar'}]},
 'hnk-exp-27':{type:'steps',caption:'Gatilho de fuga por segmento',
   steps:[{l:'Bar A/B',d:'muda por data de entrega'},{l:'Bar C/D',d:'muda por preço e caixa'},{l:'Restaurant C/D',d:'entrega e prazo'},{l:'ASI',d:'ruptura imediata'}]},
 'hnk-exp-28':{type:'bars',unit:'',caption:'Missão por território (índices)',
   data:[{l:'Área IV · maior queda',v:100,hi:1,tag:'recuperar'},{l:'PE/CE/Norte · expandir Amstel',v:70,tag:'expandir'},{l:'SP/BA · reparar diferença',v:55,tag:'diferenciar'},{l:'LGBT+ · Different 115→106',v:45,tag:'distinguir'}]}
};
